### PR TITLE
Reorganize all files into folders with prior changes

### PR DESCRIPTION
**Pull request by jamesray1**
@pirapira 

This will make the readme more visible since people don't have to scroll down a lot to get to it. As an added benefit, the repo is now more organized.

### CODE REVIEW

**Comment by pirapira** [comment]
Does this change the url of the pages?

**Comment by jamesray1** [comment]
Hmmm, links could be updated after this change if they break?

**Comment by pirapira** [comment]
No, I don't have control over all incoming links to the wiki.

**Comment by jamesray1** [comment]
People will be able to figure out how to fix links by going to https://github.com/ethereum/wiki, finding the file, and changing the link.

**Comment by pirapira** [comment]
@cdetrio that's amazing!  Right, we don't need the filed in the repo.

@jamesray1 you can also clone the wiki pages as a git repository.

**Comment by pirapira** [comment]
@jamesray1 the wiki on GitHub is backed by another git repository.

**Comment by jamesray1** [comment]
Yeah I've already cloned it.

**Comment by jamesray1** [comment]
Yeah I've already cloned it, but it's good to know that someone else is too.

**Comment by jamesray1** [comment]
Closing to replace with #575.

**Pull request closed without merging**
