### PR TITLE
Delete everything in the repo except the readme and wiki/wiki

### PR DESCRIPTION
**Pull request by jamesray1**
As per the discussion in https://github.com/ethereum/wiki/pull/573#issuecomment-379934846, @cdetrio proposed that we delete all the files in the codebase/repo (not the wiki/wiki) except the README. It seemed like @pirapira agreed.

### CODE REVIEW

**Comment by jamesray1** [comment]
@pirapira, what do you think?

**Comment by Souptacular** [comment]
As long as we have backup of the old docs for posterity I'm good with this.

**Comment by jamesray1** [comment]
Backed up locally and at https://drive.google.com/open?id=1_Z7BLs3FuHnlQ3xn1ZEcH97kogBJJ5w6.

**Comment by Souptacular** [comment]
Sgtm

**Comment by Souptacular** [comment]
Not at my PC so I can't merge. Feel free to.

**Pull request merged**
