### PR TITLE
Old before deleting all files go to wiki wiki instead

### PR DESCRIPTION
**Pull request by zachwylde00**
**Please do not open a pull request.**

This repository no longer contains any code or documentation; please edit the [wiki](https://github.com/ethereum/wiki/wiki) directly, instead.

If you're having issues editing the wiki, you could try reading the introduction to GitHub wikis,  [here](https://help.github.com/articles/about-github-wikis/).

### CODE REVIEW

**Comment by ChrisChinchilla** [comment]
Thanks @zachwylde00 but I'm not sure if I understand the point of this PR? The disclaimer is already in the read me file. Is there anything that valuable in the deleted files link?

**Comment by tojin12341za** [comment]
[https://github.com/ethereum/wiki/pull/680](url)

**Comment by syncing0x** [comment]
Duplicate of #

**Comment by zachwylde00** [comment]
negative ghostrider, sorry i had it open so long there aren't any current
ussues.

**Review by Rezabayat45 — COMMENTED** [review]
old-whitepaper-for-historical-reference.md

**Pull request closed without merging**
